# Generated by Django 5.1 on 2025-09-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_rename_address_profile_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
