# Generated by Django 5.1 on 2025-09-14 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='R', max_length=3)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('notify_new_order', models.BooleanField(default=True)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('default_report_period', models.CharField(default='week', max_length=10)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
