# Generated by Django 5.1 on 2025-09-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
    ]
