# Generated by Django 5.1 on 2025-11-10 10:40

import web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=web_app.models.product_image_upload_path),
        ),
    ]
